#!/bin/bash
groupId=$1
profile=FullAccessUserEC2
region=eu-north-1
ipAddress=$(dig @resolver1.opendns.com ANY myip.opendns.com +short)
aws ec2 authorize-security-group-ingress --group-id $groupId --protocol tcp --port 22 --cidr $ipAddress/32 --profile $profile --region $region

