version: '1'
services:
  eureka-server:
    build:
      context: .
      dockerfile: DockerfileEurekaServer
    image: eureka-server-image
    ports:
      - "8761:8761"
  db:
    image: postgres
    environment:
      POSTGRES_USER: epamtrainee
      POSTGRES_PASSWORD: epamtraineepassword
      POSTGRES_DB: epam_training_app
    ports:
      - "5433:5432"
  test-db:
    image: postgres
    environment:
      POSTGRES_USER: epamtrainee
      POSTGRES_PASSWORD: epamtraineepassword
      POSTGRES_DB: test_epam_training_app
    ports:
      - "5434:5434"
  gym-service:
    build:
      context: .
      dockerfile: DockerfileGymService
      args:
        - BUILD_PROFILE=docker-test
    image: gym-service-image
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - db
  report-service:
    build:
      context: .
      dockerfile: DockerfileReportService
    image: report-service-image
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
