version: '1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  gym-service:
    build:
      context: .
      dockerfile: DockerfileGymService
    image: gym-service-image
    ports:
      - "${GYM_PORT}:${GYM_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=GitHubActions
    depends_on:
      - db