version: '1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: epamtrainee
      POSTGRES_PASSWORD: epamtraineepassword
      POSTGRES_DB: epam_training_app
    ports:
      - "5433:5432"
  test-db:
    image: postgres
    environment:
      POSTGRES_USER: epamtrainee
      POSTGRES_PASSWORD: epamtraineepassword
      POSTGRES_DB: test_epam_training_app
    ports:
      - "5434:5434"
  gym-service:
    build:
      context: .
      dockerfile: DockerfileGymService
      args:
        - BUILD_PROFILE=docker-test
    image: gym-service-image
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
  report-service:
    build:
      context: .
      dockerfile: DockerfileReportService
    image: report-service-image
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dockerg
  activemq:
    image: apache/activemq-artemis:latest-alpine
    environment:
      ARTEMIS_USER: epamtrainee
      ARTEMIS_PASSWORD: epamtraineepassword
    ports:
      - "61616:61616"
      - "8161:8161"
  mongo:
    image: mongo
    ports:
      - "27017:27017"