version: '1'
networks:
  gymnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      gymnetwork:
        ipv4_address: 172.20.0.2
  gym-service:
    container_name: gym
    build:
      context: .
      dockerfile: DockerfileGymService
    image: gym-service-image
    volumes:
      - ./db.changelog-master.yaml:/app/db/changelog/db.changelog-master.yaml
    ports:
      - "${GYM_PORT}:${GYM_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=GitHubActions
      - GYM_PORT=${GYM_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - INDEX_PAGE=${INDEX_PAGE}
    depends_on:
      - db
    networks:
      gymnetwork:
        ipv4_address: 172.20.0.3