spring:
  datasource:
    username: epamtrainee
    password: epamtraineepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/epam_training_app
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
server:
  port: 8081
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test_epam_training_app
  jpa:
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: db/changelog/db.test-changelog-master.xml
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stg

---
spring:
  config:
    activate:
      on-profile: prod

