spring:
  datasource:
    username: epamtrainee
    password: epamtraineepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
my-props:
  jwt:
    secret-key: wE+KbVBGeWh45kQ6oN7TPAzRQIOqnTO5fPbyk0bLyoE=
    max-attempts: 5
    cold-pause-min: 1
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/epam_training_app
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator/
      path-mapping:
        prometheus: prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test_epam_training_app
  jpa:
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: db/changelog/db.test-changelog-master.xml
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stg

---
spring:
  config:
    activate:
      on-profile: prod

