spring:
  application:
    name: report-service
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: local
    import: classpath:secretStoreLocal.yaml
  data:
    mongodb:
      uri: mongodb://localhost:27017/gymWorkloads
---
spring:
  config:
    activate:
      on-profile: docker
    import: classpath:secretStoreDocker.yaml
  data:
    mongodb:
      uri: mongodb://mongo:27017/gymWorkloads
---
spring:
  config:
    activate:
      on-profile: without
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: cloud
    import: classpath:secretStoreCloud.yaml
  aws:
    brokerUrl: https://sqs.eu-north-1.vpce.amazonaws.com/767397684799/Gym-to-Report-Queue
server:
  port: 8081