spring:
  application:
    name: report-service
server:
  port: 8082
---
spring:
  profiles:
    active: local
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles:
    active: docker
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka