spring:
  application:
    name: report-service
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: local
    import: classpath:secretStoreLocal.yaml
  data:
    mongodb:
      uri: mongodb://localhost:27017/gymWorkloads
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: docker
    import: classpath:secretStoreDocker.yaml
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka