name: CI/CD for DigitalOcean

on:
  push:
    branches:
      - 'digitalOcean'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH: ${{ secrets.DIGITALOCEAN_SSH_KEY}}
      USER: ${{ secrets.DIGITALOCEAN_DROPLET_USER }}
      IP: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Common
        run: mvn clean install
        working-directory: ./Common
      - name: Build GYM
        run: mvn clean install -Dspring.profiles.active=GitHubActions
        working-directory: ./GymService
        env:
          ACTIVEMQ_PASSWORD: ${{ secrets.ACTIVEMQ_PASSWORD }}
          ACTIVEMQ_URL: ${{ secrets.ACTIVEMQ_URL }}
          ACTIVEMQ_USERNAME: ${{ secrets.ACTIVEMQ_USERNAME }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY}}
          GYM_PORT: ${{ secrets.GYM_PORT}}
      - name: Build REPORT
        run: mvn clean install -Dspring.profiles.active=GitHubActions
        working-directory: ./ReportService
        env:
          ACTIVEMQ_PASSWORD: ${{ secrets.ACTIVEMQ_PASSWORD }}
          ACTIVEMQ_URL: ${{ secrets.ACTIVEMQ_URL }}
          ACTIVEMQ_USERNAME: ${{ secrets.ACTIVEMQ_USERNAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY}}
          REPORT_PORT: ${{ secrets.REPORT_PORT}}
      - name: Copy files to DigitalOcean
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          ssh-keyscan -H $IP >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private.key
          scp -r ./GymService/target/GymService*.jar $USER@$IP:~/app
          scp -r ./ReportService/target/ReportService*.jar $USER@$IP:~/app
          scp -r ./run.sh $USER@$IP:~/app
          scp -r ./docker-compose.yml $USER@$IP:~/app
          scp -r ./DockerfileGymService $USER@$IP:~/app
          scp -r ./DockerfileReportService $USER@$IP:~/app
        shell: bash
      - name: Set environment variables on DigitalOcean
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private.key
          ssh $USER@$IP "echo 'export DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export DATABASE_NAME=${{ secrets.DATABASE_NAME }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export DATABASE_PORT=${{ secrets.DATABASE_PORT }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export GYM_PORT=${{ secrets.GYM_PORT }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export REPORT_PORT=${{ secrets.REPORT_PORT }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export ACTIVEMQ_PORT_JMS=${{ secrets.ACTIVEMQ_PORT_JMS }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export ACTIVEMQ_PORT=${{ secrets.ACTIVEMQ_PORT }}' >> ~/.bashrc"
          ssh $USER@$IP "echo 'export MONGO_PORT=${{ secrets.MONGO_PORT }}' >> ~/.bashrc"
      - name: Start application
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private.key
          ssh $USER@$IP "source ~/.bashrc cd ~/app && docker compose build && docker compose up -d"