name: CI/CD for DigitalOcean

on:
  push:
    branches:
      - 'digitalOcean'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Common
        run: mvn clean install
        working-directory: ./Common
      - name: Build GYM
        run: mvn clean install
        working-directory: ./GymService
      - name: Build REPORT
        run: mvn clean install
        working-directory: ./ReportService

