name: CI/CD for DigitalOcean

on:
  push:
    branches:
      - 'digitalOcean'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Common
        run: mvn clean install
        working-directory: ./Common
      - name: Build GYM
        run: mvn clean test -Dspring.profiles.active=GitHubActions
        working-directory: ./GymService
        env:
          ACTIVEMQ_PASSWORD: ${{ secrets.ACTIVEMQ_PASSWORD }}
          ACTIVEMQ_URL: ${{ secrets.ACTIVEMQ_URL }}
          ACTIVEMQ_USERNAME: ${{ secrets.ACTIVEMQ_USERNAME }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY}}
      - name: Build REPORT
        run: mvn clean install
        working-directory: ./ReportService

